# Generated by Django 4.1.2 on 2022-10-10 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customusermodel_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='phone',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number format.', regex='^\\+?(38)?\\(?0[1-9]{2}\\)?[0-9]{2}-?[0-9]{3}-?[0-9]{2}$')]),
        ),
    ]
